version: 2.1

orbs:
  node: circleci/node@5.0.1
  #to import docker
  docker: circleci/docker@2.4.0
  heroku: circleci/heroku@2.0.0

jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
        pkg-manager: npm
      - run: |
          echo "Installing dep..."
          npm install
  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "running t  st...."
          npm test
  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: sukarno/assignment
          tag: v3.4.5
      - docker/push:
          image: sukarno/assignment
          tag: v3.4.5
  # deploy:
  #   docker:
  #     - image: cimg/node:16.10
  #   steps:
  #     - setup_remote_docker
  #     - heroku/install
  #     - checkout
  #     - run:
  #         name: Heroku Container Push
  #         command: |
  #           heroku container:login
  #           heroku container:push web -a sukarno-su-ops
  #           heroku container:release web -a sukarno-su-ops
  pull-and-deploy:
    docker:
      - images: cimg/node:16.0
    steps:
      - setup_remote_docker
      - heroku/install
      - docker/pull:
          image: sukarno/assignment:v3.4.5
      - run:
          name: Heroku From Docker Hub
          command: |
            heroku container:login
            docker tag sukarno/assignment:v.3.4.5 registry.heroku.com/sukarno-su-devops/web
            docker push registry.heroku.com/sukarno-su-devops/web
            heroku container:release web -a sukarno-su-devops

workflows:
  simple_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - build-and-push:
          requires:
            - test
      - pull-and-deploy:
          requires:
            - build